/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lesson6.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * CategoryDto
 */

@JsonInclude(JsonInclude.Include.NON_NULL)
@Data
public class CategoryDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @JsonProperty(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_PRODUCTS = "products";
  @JsonProperty(SERIALIZED_NAME_PRODUCTS)
  private List<ProductDto> products = new ArrayList<>();

  public static final String SERIALIZED_NAME_TITLE = "title";
  @JsonProperty(SERIALIZED_NAME_TITLE)
  private String title;

  public CategoryDto() { 
  }

  public CategoryDto id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/


  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public CategoryDto products(List<ProductDto> products) {
    
    this.products = products;
    return this;
  }

  public CategoryDto addProductsItem(ProductDto productsItem) {
    if (this.products == null) {
      this.products = new ArrayList<>();
    }
    this.products.add(productsItem);
    return this;
  }

   /**
   * Get products
   * @return products
  **/


  public List<ProductDto> getProducts() {
    return products;
  }


  public void setProducts(List<ProductDto> products) {
    this.products = products;
  }


  public CategoryDto title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/


  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CategoryDto categoryDto = (CategoryDto) o;
    return Objects.equals(this.id, categoryDto.id) &&
        Objects.equals(this.products, categoryDto.products) &&
        Objects.equals(this.title, categoryDto.title);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, products, title);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CategoryDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    products: ").append(toIndentedString(products)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
