/*
 * Api Documentation
 * Api Documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package lesson6.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.With;

import java.util.Objects;


/**
 * Product dto in the application.
 */


@JsonInclude(JsonInclude.Include.NON_NULL)
@Getter
@With
@AllArgsConstructor
@Data
public class ProductDto {
  public static final String SERIALIZED_NAME_ID = "id";
  @JsonProperty(SERIALIZED_NAME_ID)
  private Long id;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @JsonProperty(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @JsonProperty(SERIALIZED_NAME_PRICE)
  private Integer price;

  public static final String SERIALIZED_NAME_CATEGORY_TITLE = "categoryTitle";
  @JsonProperty(SERIALIZED_NAME_CATEGORY_TITLE)
  private String categoryTitle;

  public ProductDto() { 
  }

  public ProductDto id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of the product. No two products can have the same id.
   * @return id
  **/


  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public ProductDto title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Title of the product.
   * @return title
  **/


  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public ProductDto price(Integer price) {
    
    this.price = price;
    return this;
  }

   /**
   * Price of the product.
   * @return price
  **/


  public Integer getPrice() {
    return price;
  }


  public void setPrice(Integer price) {
    this.price = price;
  }


  public ProductDto categoryTitle(String categoryTitle) {
    
    this.categoryTitle = categoryTitle;
    return this;
  }

   /**
   * Category title of the product.
   * @return categoryTitle
  **/

  public String getCategoryTitle() {
    return categoryTitle;
  }


  public void setCategoryTitle(String categoryTitle) {
    this.categoryTitle = categoryTitle;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductDto productDto = (ProductDto) o;
    return Objects.equals(this.id, productDto.id) &&
        Objects.equals(this.title, productDto.title) &&
        Objects.equals(this.price, productDto.price) &&
        Objects.equals(this.categoryTitle, productDto.categoryTitle);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, price, categoryTitle);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductDto {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    categoryTitle: ").append(toIndentedString(categoryTitle)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
